name: compressed-size
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: compressed-size-action
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: 'dist/!(*.js.map)'
          build-script: build
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: compressed-size-action
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: 'test/fixtures/**/dist/!(*.map)'
          # We're using this to report size differences, not test, so update snapshots if they fail.
          # The CI can catch the test failures instead.
          build-script: 'test -- -u'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
