name: compressed-size
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: compressed-size-action
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: 'dist/!(*.js.map)'
          build-script: build
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
